config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  get 'payment_notification/create'

  resources :subscrptions
  resources :shippings
  resources :contacts
  resources :addresses
  # devise_for :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :brands
  resources :categories
  resources :customs
  resources :faqs
  resources :order_statuses
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders
  resources :charges
  get 'home/index' 
  root 'home#index'
  get 'home/login_form'
  get 'home/forget_psw'
  get 'home/signup_form'
  get 'home/checkout'
  get 'home/checkout_shipping'
  get 'home/contact'
  post 'home/contact_us_mailer'
  get 'home/about_us'
  get 'home/delivery_policy'
  get 'home/privarcy_policy'
  get 'home/terms_of_delivery'
  get 'home/return'
  get 'paypal/checkout', to: 'subscriptions#paypal_checkout'
  resources :payment_notification, only: [:create]

end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/brand.rb
class Brand < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :products
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :imageable, polymorphic: true, optional: true
	mount_uploader :image, ImageUploader
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :order_status, optional: true
	  has_many :order_items
	  has_many :products
	  before_create :set_order_status
	  before_save :update_subtotal
	  belongs_to :user, optional: true
	  has_many :payment_notifications

		def subtotal
		    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
		end
		
	private
		def set_order_status
		    self.order_status_id = 1
		end

	    def update_subtotal
	        self[:sub_total] = sub_total
	    end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order ,optional: true
  	belongs_to :product, optional: true
  	validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
	validate :order_present
	validate :product_present
	before_save :finalize

	    def unit_price
	      if persisted?
	        self[:unit_price]
	      else
	        product.price
	      end
	    end

	    def total_price
	      unit_price * quantity
	    end

		def self.paypal_url(return_path)
		    values = {
		        business: "ankita.dangi-facilitator@zingbytes.com",
		        cmd: "_xclick",
		        upload: 1,
		        return: return_path,	    }
		 #    <% debuger
		 #    		    OrderItem.each do |item|
			#     values.merge!({
			#       "item_name" => item.product.name,
			#       "item_number" => item.id,
			#       "quantity" => item.quantity
			#     })
			# end
		   "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
	  	end
	  	
	  private
	    def product_present
	      if product.nil?
	        errors.add(:product, "is not valid or is not active.")
	      end
	    end

	    def order_present
	      if order.nil?
	        errors.add(:order, "is not a valid order.")
	      end
	    end

	    def finalize
	      self[:unit_price] = unit_price
	      self[:total_price] = quantity * self[:unit_price]
	    end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :category
	belongs_to :brand
	has_many :images, as: :imageable
	accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true, update_only: true
	# default_scope { where(active: true) }
	def self.search(title)
      if title
        where('title LIKE ?', "%#{title}%")
      else
        all
      end
    end

end

app/models/shipping.rb
class Shipping < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :confirmable, :omniauthable
  include DeviseTokenAuth::Concerns::User
	has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 		def admin?
  	     	return self.admin ? true : false
        end
        
end

app/controllers/shippings_controller.rb
class ShippingsController < ApplicationController
  before_action :set_shipping, only: [:show, :edit, :update, :destroy]

  # GET /shippings
  # GET /shippings.json
  def index
    @shippings = Shipping.all
  end

  # GET /shippings/1
  # GET /shippings/1.json
  def show
  end

  # GET /shippings/new
  def new
    @shipping = Shipping.new
  end

  # GET /shippings/1/edit
  def edit
  end

  # POST /shippings
  # POST /shippings.json
  def create
    @shipping = Shipping.new(shipping_params)

      if @shipping.save
        redirect_to orders_path
      else
       render 'new'
      end
  end

  # PATCH/PUT /shippings/1
  # PATCH/PUT /shippings/1.json
  def update
      if @shipping.update(shipping_params)
        redirect_to orders_path
      else
        render 'edit'
      end
  end


  # DELETE /shippings/1
  # DELETE /shippings/1.json
  def destroy
    @shipping.destroy
    respond_to do |format|
      format.html { redirect_to shippings_url, notice: 'Shipping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipping
      @shipping = Shipping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipping_params
      params.require(:shipping).permit(:express, :standard)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customs_helper.rb
module CustomsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/views/shippings/_form.html.erb
<%= form_for Shipping.new do |form| %>
        <br>
          <div class="row">
            <div class="col-md-6">
            <h4>United States - Standard shipping</h4>
            <div class="radio">
            <label class="color-active">
              <%= form.radio_button :standard, id: :shipping_standard %>
    
            $14.00
            </label>
            </div>
            Standard shipping is 3-5 business days.
            Keep in mind that production may take up to 2 weeks.
          </div>
          <div class="col-md-6">
            <h4>United States - Express shipping</h4>
            <div class="radio">
            <label class="color-active">
            <%= form.radio_button :express, id:24 %>
            $24.00
            </label>
            </div>
            Express shipping is 2-3 business days.
            Keep in mind that production may take up to 2 weeks.
          </div>
        </div>
        <hr>
        <%= form.submit "Save and continue", class: "btn btn-danger checkout_submit"%>
<% end %> 
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <div class="widget-block">
        <strong class="title">ORDER SUMMARY</strong>
        <dl class="summary">
        <dt>Subtotal</dt>
        <dd>$74.00</dd>
        <dt>Shipping total: </dt>
        <dd>$14.00</dd>
        <dt>Taxes: </dt>
        <dd><strong>-</strong></dd>
        <dt><strong>Order Total</strong></dt>
        <dd><strong>$88.00</strong></dd>
        </dl>
        </div>
        <div class="widget-block">
        <strong class="title">APPLY DISCOUNT</strong>
        <form accept-charset="UTF-8" action="/orders/CB36121007/apply_coupon" class="discount-form" id="update-cart" method="post"><div style="display:none"><input name="utf8" type="hidden" value="&#x2713;" /><input name="_method" type="hidden" value="patch" /><input name="authenticity_token" type="hidden" value="YFYHhbtGQiROZYJwZklrSt/CV9WHW89pQjY459FOnJY=" /></div>
        <div class="form-group">
        <input type="text" name="order[coupon_code]" class="form-control" placeholder="code">
        <input type="hidden" name="order[state]" value="delivery" class="form-control">
        </div>
        <input type="submit" value="Apply Coupon" class="btn btn-default">
       

app/views/shippings/edit.html.erb
<h1>Editing Shipping</h1>

<%= render 'form', shipping: @shipping %>

<%= link_to 'Show', @shipping %> |
<%= link_to 'Back', shippings_path %>

app/views/shippings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shippings</h1>

<table>
  <thead>
    <tr>
      <th>Express</th>
      <th>Standard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shippings.each do |shipping| %>
      <tr>
        <td><%= shipping.express %></td>
        <td><%= shipping.standard %></td>
        <td><%= link_to 'Show', shipping %></td>
        <td><%= link_to 'Edit', edit_shipping_path(shipping) %></td>
        <td><%= link_to 'Destroy', shipping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shipping', new_shipping_path %>

app/views/shippings/new.html.erb
<h1>New Shipping</h1>

<%= render 'form', shipping: @shipping %>

<%= link_to 'Back', shippings_path %>

app/views/shippings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Express:</strong>
  <%= @shipping.express %>
</p>

<p>
  <strong>Standard:</strong>
  <%= @shipping.standard %>
</p>

<%= link_to 'Edit', edit_shipping_path(@shipping) %> |
<%= link_to 'Back', shippings_path %>