config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  get 'payment_notification/create'

  resources :subscrptions
  resources :shippings
  resources :contacts
  resources :addresses
  # devise_for :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :brands
  resources :categories
  resources :customs
  resources :faqs
  resources :order_statuses
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders
  resources :charges
  get 'home/index' 
  root 'home#index'
  get 'home/login_form'
  get 'home/forget_psw'
  get 'home/signup_form'
  get 'home/checkout'
  get 'home/checkout_shipping'
  get 'home/contact'
  post 'home/contact_us_mailer'
  get 'home/about_us'
  get 'home/delivery_policy'
  get 'home/privarcy_policy'
  get 'home/terms_of_delivery'
  get 'home/return'
  get 'paypal/checkout', to: 'subscriptions#paypal_checkout'
  resources :payment_notification, only: [:create]

end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/brand.rb
class Brand < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :products
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :imageable, polymorphic: true, optional: true
	mount_uploader :image, ImageUploader
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :order_status, optional: true
	  has_many :order_items
	  has_many :products
	  before_create :set_order_status
	  before_save :update_subtotal
	  belongs_to :user, optional: true
	  has_many :payment_notifications

		def subtotal
		    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
		end
		
	private
		def set_order_status
		    self.order_status_id = 1
		end

	    def update_subtotal
	        self[:sub_total] = sub_total
	    end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order ,optional: true
  	belongs_to :product, optional: true
  	validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
	validate :order_present
	validate :product_present
	before_save :finalize

	    def unit_price
	      if persisted?
	        self[:unit_price]
	      else
	        product.price
	      end
	    end

	    def total_price
	      unit_price * quantity
	    end

		def self.paypal_url(return_path)
		    values = {
		        business: "ankita.dangi-facilitator@zingbytes.com",
		        cmd: "_xclick",
		        upload: 1,
		        return: return_path,	    }
		 #    <% debuger
		 #    		    OrderItem.each do |item|
			#     values.merge!({
			#       "item_name" => item.product.name,
			#       "item_number" => item.id,
			#       "quantity" => item.quantity
			#     })
			# end
		   "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
	  	end
	  	
	  private
	    def product_present
	      if product.nil?
	        errors.add(:product, "is not valid or is not active.")
	      end
	    end

	    def order_present
	      if order.nil?
	        errors.add(:order, "is not a valid order.")
	      end
	    end

	    def finalize
	      self[:unit_price] = unit_price
	      self[:total_price] = quantity * self[:unit_price]
	    end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :category
	belongs_to :brand
	has_many :images, as: :imageable
	accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true, update_only: true
	# default_scope { where(active: true) }
	def self.search(title)
      if title
        where('title LIKE ?', "%#{title}%")
      else
        all
      end
    end

end

app/models/shipping.rb
class Shipping < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :confirmable, :omniauthable
  include DeviseTokenAuth::Concerns::User
	has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 		def admin?
  	     	return self.admin ? true : false
        end
        
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
    	@order_items = current_order.order_items
    	@orders= Order.all
    	end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customs_helper.rb
module CustomsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_shopping.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
  <h1>
    There are no items in your shopping cart.Please <%= link_to "go back", root_path %> and add some items to your cart.</h1>
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', custom_snapbacks: order_item.custom_snapback, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <% current_user.orders.each do |order| %>
    <% order.order_items.each do |item| %>
      <tbody>
        <tr>
          <td class="col-photo" data-th="Image">
              <%= image_tag item.product.images.first.image.url, class: "img-responsive thumbnail", width: "90", height: "90" %>
                <img id="output" class="centered" />
                  <div class="centered myText" id="edit">



                  </div>
          </td>
          <td class="col-name" data-hook="cart_item_description">
            <strong class="title"><%= item.product.title %></strong>
          </td>
          <td class="col-unit-price"><strong class="price">$<%= item.unit_price %></strong></td>
          <td class="col-qty">
            <%= item.quantity %>
          </td>
          <td class="col-price">
            <%= item.total_price %>
          </td>
          <td class="col-actions">
            <h4 style align="right"><%= link_to "X",order_path(order), method: :delete, class: "delete_line_item", data: { confirm: 'Are you sure?' } %></h4>
            <a href="/products/<%= item.product.id %>" class= "icon-edit"></a>
          </td>
        </tr>
      </tbody>
    <% end %>
  <% end %>
 
    <tfoot>
      <tr>
        <td colspan="6">
          <dl class="summary">
            <dt>Subtotal</dt>
            <dd><%= number_to_currency current_order.subtotal %></dd>
            <dt><strong>Order Total</strong></dt>
            <dd><strong><%= number_to_currency current_order.subtotal %></strong></dd>
          </dl>
        </td>
      </tr>
    </tfoot>
  </table>
<%# end %>

app/views/carts/show.html.erb
<div class="container-fluid">
    <div class="cart-section">
      	<div class="row">
      		<div class="col-sm-8 col-md-9">
      			<% if current_order.order_items.size == 0 %>
				  <div class="cart-section">
				    <div class="row">
				      <div class="col-sm-8 col-md-9">
				      <h3><center><strong>Your cart is empty</strong></center></h3>
				      <center><a href="/home/index" class="btn btn-default">Continue shopping</a></center>
				      </div>
				    </div>
				  </div>
				<% else %>
					<div class="shopping-cart">
						<div class="well">
					  		<div class="row">
					    		<div class="col-sm-8 col-md-9">
					    			<table class="cart-table table">
						      		<thead>
						            <tr>
						              <th class="col-photo">ITEM</th>
						              <th class="col-name"></th>
						              <th class="col-unit-price">UNIT PRICE</th><br>
						              <th class="col-qty">QTY</th>
						              <th class="col-price">Total</th>
						              <th class="col-actions"></th>
						            </tr>
						          	</thead>
									<%= render "shopping_cart", current_user: current_user %>
								</table>
								</div>
							</div>
						</div>
					</div>
				<% end %>
			</div>
			<div class="col-sm-4 col-md-3">
	          <div class="widget-block">
	            <strong class="title">ORDER SUMMARY</strong>
	              <dl class="summary">
	                <dt>Subtotal</dt>
	                  <dd><%= number_to_currency current_order.subtotal %></dd>
	                <dt>Shipping Total: </dt>
	                  <dd><strong>-</strong></dd>
	                <dt>Total Items:</dt>
	                  <dd><strong><%= current_order.order_items.size %></strong></dd>
	                <dt><strong>Order Total</strong></dt>
	                  <dd><strong><%= number_to_currency current_order.subtotal %></strong></dd>
	              </dl>
	              	<% if user_signed_in? %>
	                	<%= link_to 'CHECKOUT NOW', home_checkout_path, class: "btn btn-danger" %>
	                <% else %>
	                	<%= link_to 'CHECKOUT NOW', home_login_form_path, class: "btn btn-danger" %>
	                <% end %>
	            <div class="link">
	                <%= link_to'Continue Shopping', home_index_path %>
	            </div>
	          </div>
	          <div id="alert-pop">
	            <div class="modal fade" id="cart_delete_warning" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	              <div class="modal-dialog modal-md">
	                <div class="modal-content">
	                  <div class="modal-header">
	                    <br>
	                      <h4 class="text-center">Are you sure you want to remove this item from your cart?</h4>
	                  </div>
	                  <div class="modal-body">
	                    <div class="row">
	                      <div class="col-sm-12 text-center">
	                        <form accept-charset="UTF-8" action="/orders/CB13881788/remove_line_item" method="post"><div style="display:none"><!-- <input name="utf8" type="hidden" value="&#x2713;" /><input name="_method" type="hidden" value="delete" /><input name="authenticity_token" type="hidden" value="sKq6pXGLqUMwvjqqOnK0DEcF3xU4fDN0M4Y6hJv44e8=" /> --></div>
	                        <input id="line_item" name="line_item" type="hidden" />
	                        <br>
	                        <input class="ok btn btn-danger delete-item-from-cart" name="commit" type="submit" value="OK" />
	                        <button class="btn btn-default" data-dismiss="modal" value="Cancel">Cancel</button>
	                        <br>
	                        <br>
	                        </form> 
	                      </div>
	                    </div>
	                  </div>
	                </div>
	              </div>
	            </div>
	          </div>
	          <div class="widget-block">
	            <strong class="title">APPLY DISCOUNT</strong>
	              <!-- <form accept-charset="UTF-8" action="/cart" class="discount-form" id="update-cart" method="post"><div style="display:none"><input name="utf8" type="hidden" value="&#x2713;" /><input name="_method" type="hidden" value="patch" /><input name="authenticity_token" type="hidden" value="sKq6pXGLqUMwvjqqOnK0DEcF3xU4fDN0M4Y6hJv44e8=" /></div>
	                <div class="form-group">
	                  <input type="text" name="order[coupon_code]" class="form-control" placeholder="code">
	                </div>
	                <input type="submit" value="Apply Coupon" class="btn btn-default">
	              </form>  -->
	          </div>
			</div>
		</div>
	</div>
</div>