config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  get 'payment_notification/create'

  resources :subscrptions
  resources :shippings
  resources :contacts
  resources :addresses
  # devise_for :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :brands
  resources :categories
  resources :customs
  resources :faqs
  resources :order_statuses
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders
  resources :charges
  get 'home/index' 
  root 'home#index'
  get 'home/login_form'
  get 'home/forget_psw'
  get 'home/signup_form'
  get 'home/checkout'
  get 'home/checkout_shipping'
  get 'home/contact'
  post 'home/contact_us_mailer'
  get 'home/about_us'
  get 'home/delivery_policy'
  get 'home/privarcy_policy'
  get 'home/terms_of_delivery'
  get 'home/return'
  get 'paypal/checkout', to: 'subscriptions#paypal_checkout'
  resources :payment_notification, only: [:create]

end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/brand.rb
class Brand < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :products
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :imageable, polymorphic: true, optional: true
	mount_uploader :image, ImageUploader
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :order_status, optional: true
	  has_many :order_items
	  has_many :products
	  before_create :set_order_status
	  before_save :update_subtotal
	  belongs_to :user, optional: true
	  has_many :payment_notifications

		def subtotal
		    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
		end
		
	private
		def set_order_status
		    self.order_status_id = 1
		end

	    def update_subtotal
	        self[:sub_total] = sub_total
	    end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order ,optional: true
  	belongs_to :product, optional: true
  	validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
	validate :order_present
	validate :product_present
	before_save :finalize

	    def unit_price
	      if persisted?
	        self[:unit_price]
	      else
	        product.price
	      end
	    end

	    def total_price
	      unit_price * quantity
	    end

		def self.paypal_url(return_path)
		    values = {
		        business: "ankita.dangi-facilitator@zingbytes.com",
		        cmd: "_xclick",
		        upload: 1,
		        return: return_path,	    }
		 #    <% debuger
		 #    		    OrderItem.each do |item|
			#     values.merge!({
			#       "item_name" => item.product.name,
			#       "item_number" => item.id,
			#       "quantity" => item.quantity
			#     })
			# end
		   "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
	  	end
	  	
	  private
	    def product_present
	      if product.nil?
	        errors.add(:product, "is not valid or is not active.")
	      end
	    end

	    def order_present
	      if order.nil?
	        errors.add(:order, "is not a valid order.")
	      end
	    end

	    def finalize
	      self[:unit_price] = unit_price
	      self[:total_price] = quantity * self[:unit_price]
	    end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :category
	belongs_to :brand
	has_many :images, as: :imageable
	accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true, update_only: true
	# default_scope { where(active: true) }
	def self.search(title)
      if title
        where('title LIKE ?', "%#{title}%")
      else
        all
      end
    end

end

app/models/shipping.rb
class Shipping < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :confirmable, :omniauthable
  include DeviseTokenAuth::Concerns::User
	has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 		def admin?
  	     	return self.admin ? true : false
        end
        
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
	before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @products = Product.all
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :image, :product_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customs_helper.rb
module CustomsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/_form.html.erb
<%= form_with(model: brand, local: true) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :brand_name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :brand_image %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id, id: :brand_product_id %>
  </div>

 
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category name </th>
      <th>About</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= image_tag brand.image.url %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Brand Detail </h1>
<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>



<h1> All Products Of Brand </h1>

<%= Brand.products.each do |product| %><br>
<strong>id:</strong>
<td> <%= product.id %></td><br>
<strong>Image:</strong>
<td><%= image_tag product.image.url, class: "img-responsive" if product.image.present? %></td><br>
<strong>title:</strong>
  <td> <%= product.title %></td><br>

<% end %>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>